import "./globals.css";
import { ModalProvider } from "@/context/ModelContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`max-w-[390px]  `}
      >
        <ModalProvider>
          {children}

        </ModalProvider>
      </body>
    </html>
  );
}
